<h1>Add New Post</h1>
<hr>
<div class="six columns">
    <form method="POST" action="/helloworld/post/insert">
        <div class="row">
            <div class="three columns u-text-right">
                <?= __('Name:'); ?>
            </div>
            <div class="nine columns">
                <input type="text" name="name" id="name">
            </div>
        </div>
        
        <div class="row">
            <div class="three columns u-text-right">
                <?= __('Content:'); ?>
            </div>
            <div class="nine columns">
                <textarea name="post_content" id="post_content" rows="50"></textarea>
            </div>
        </div>
                
        <div class="row">
            <div class="three columns u-text-right">
                <?= __('URL Key:'); ?>
            </div>
            <div class="nine columns">
                <input type="text" name="url_key" id="url_key">
            </div>
        </div>
                        
        <div class="row">
            <div class="three columns u-text-right">
                <?= __('Tags:'); ?>
            </div>
            <div class="nine columns">
                <input type="text" name="tags" id="tags">
            </div>
        </div>
                                
        <div class="row">
            <div class="three columns u-text-right">
                <?= __('Status:'); ?>
            </div>
            <div class="three columns">
                <select name="status" id="status">
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                </select>
            </div>
        </div>
                        
        <div class="row u-text-right">
            <a href="/helloworld/post/index" class="button">cancel</a>
            <button class="button-primary">Save</button>
        </div>
    </form>
</div>