
<div class="row u-text-right">
    <a class="button" href="/helloworld/post/create">Add New Post</a>
</div>
<table>
<tr>
<td>ID</td>
<td>TITLE</td>
<td>POST</td>
<td>STATUS</td>
<td>DATE</td>
</tr>
<?php foreach($block->getPostCollection() as $item): ?>
    <tr>
        <td><?= $item->getPostId(); ?></td>
        <td><?= $item->getName(); ?></td>
        <td><?= $item->getPostContent(); ?></td>
        <td><?= $item->getStatus() ? 'Active' : 'Inactive'; ?></td>
        <td><?= $block->carbonParse($item->getCreatedAt())->diffForHumans(); ?></td>
        <td>
            <a class="button" href="/helloworld/post/edit/id/<?= $item->getPostId(); ?>">Update</a>
            <a class="button btn-delete" href="/helloworld/post/delete/id/<?= $item->getPostId(); ?>" onclick="confirmDelete">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>