<ul class="quick-links">
    <li class="links-container">
        <span data-mage-init='{"dropdown":{}}' data-toggle="dropdown">About</span>
        <div class="customer-menu" data-target="dropdown">
            <ul class="header links">
                <li><a href="/contacts">Link 1</a></li>
                <li><a href="/contacts">Link 2</a></li>
                <li><a href="/contacts">Link 3</a></li>
            </ul>
        </div>
    </li>
</ul>