<ul class="bxslider">
     <li><img style="width: 100%" src="<?=$block->getViewFileUrl('Mageplaza_HelloWorld::images/churva-01.jpg'); ?>"/></li>
     <li><img style="width: 100%" src="<?=$block->getViewFileUrl('Mageplaza_HelloWorld::images/churva-01.jpg'); ?>"/></li>
     <li><img style="width: 100%" src="<?=$block->getViewFileUrl('Mageplaza_HelloWorld::images/churva-01.jpg'); ?>"/></li>
 </ul>


<script>
var j = jQuery.noConflict();
j('.bxslider').bxSlider({
    mode: 'horizontal',
    captions: true,
    auto: true,
});
</script>