
<?php
$categories = $this->getStoreCategories(true,false,true);
$categoryHelper = $this->getCategoryHelper();
?>

<h3>Categories</h3>
<ul>
    <?php
    foreach($categories as $category):
        if (!$category->getIsActive()) {
            continue;
        }
        $count = $this->getProductCount($category->getId());
    ?>


        <li><a href="<?= $categoryHelper->getCategoryUrl($category) ?>"><?= $category->getName() ?><?=$count?"({$count})":''?></a></li>
        <?php if($childrenCategories = $this->getChildCategories($category)): ?>
            <ul>
                <?php
                foreach($childrenCategories as $childrenCategory):
                    if (!$childrenCategory->getIsActive()) {
                        continue;
                    }
                    $count = $this->getProductCount($childrenCategory->getId());
                ?>
                    <li><a href="<?= $categoryHelper->getCategoryUrl($childrenCategory) ?>"><?= $childrenCategory->getName() ?><?=$count?"({$count})":''?></a></li>
                <?php endforeach;?>
            </ul>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
 