
<?php $post = $block->getPost(); ?>

<h1>Edit '<?= $post->getName(); ?>'</h1>
<hr>
<div class="six columns">
    <form method="POST" class="form" id="posts-form" action="/helloworld/post/update/id/<?= $post->getId(); ?>">
            <fieldset class="fieldset">
                <div class="field required">
                <legend class="legend"><span><?php echo __('Name') ?></span></legend><br>
            <div class="control">
                <input type="text" name="name" id="name" value="<?= $post->getName(); ?>" title="<?php echo __('Name') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
                </div>
            </fieldset>

            <fieldset class="fieldset">
                <div class="field required">    
                <legend class="legend"><span><?php echo __('URL Key') ?></span></legend><br>
                    <div class="control">
                        <input type="text" name="url_key" id="url_key" value="<?= $post->getUrlKey(); ?>" title="<?php echo __('URL Key') ?>" class="input-text" data-validate="{required:true}">
                    </div>
                </div>
            </fieldset>

            <fieldset class="fieldset">
                <div class="field required">
                <legend class="legend"><span><?php echo __('Tags') ?></span></legend><br>
                    <div class="control">
                        <input type="text" name="tags" id="tags" value="<?= $post->getTags(); ?>" title="<?php echo __('Tags') ?>" class="input-text" data-validate="{required:true}">
                    </div>
                </div>
            </fieldset>

            <fieldset class="fieldset">
                <legend class="legend"><span><?php echo __('Status') ?></span></legend><br>
                <div class="field required">
                <select name="status" id="status">
                    <option <?php if($post->getStatus() == 0) echo 'selected'; ?> value="0" selected>Inactive</option>
                    <option <?php if($post->getStatus() == 1) echo 'selected'; ?> value="1">Active</option>
                </select>
                </div>
            </fieldset>

            <fieldset class="fieldset">
                <legend class="legend"><span><?php echo __('Content') ?></span></legend><br>
                <div class="field required">
                    <div class="control">
                        <textarea name="post_content" id="post_content" title="<?php echo __('Tags') ?>" class="input-text" data-validate="{required:true}" rows="10"><?= trim($post->getPostContent()); ?></textarea>
                    </div>
                </div>
            </fieldset>
                        
        <div class="row u-text-right">
            <a href="/helloworld/post/index" class="button">cancel</a>
            <button class="button-primary">Update</button>
        </div>
    </form>
</div>

<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
 
   var dataForm = $('#posts-form');
   dataForm.mage('validation', {});
 
});
</script>